<?php

/**
 * @autor marcelo-brad rj
 * @contato Tel: +55 (21) 98132-5441
 * @contato Email: contato@kdkhost.com.br
 * @contato Telegram: @MARCELO_BRAD
 * @contato Instagram: @marcelobradrj
 * @contato WhatsApp: 5521981325441
 */

return [
    'dashboard' => [
        'name' => 'Dashboard',
        'description' => 'Painel principal com resumo do sistema',
        'active' => true,
        'version' => '1.0.0',
        'order' => 1,
        'icon' => 'fas fa-tachometer-alt',
        'route_prefix' => 'admin',
        'dependencies' => [],
    ],
    'pages' => [
        'name' => 'Páginas',
        'description' => 'Gerenciamento de páginas estáticas e institucionais',
        'active' => true,
        'version' => '1.0.0',
        'order' => 2,
        'icon' => 'fas fa-file-alt',
        'route_prefix' => 'admin/pages',
        'dependencies' => [],
    ],
    'blog' => [
        'name' => 'Blog',
        'description' => 'Gerenciamento de notícias, posts e categorias',
        'active' => true,
        'version' => '1.0.0',
        'order' => 3,
        'icon' => 'fas fa-newspaper',
        'route_prefix' => 'admin/blog',
        'dependencies' => [],
    ],
    'agenda' => [
        'name' => 'Agenda',
        'description' => 'Agenda de compromissos e eventos públicos',
        'active' => true,
        'version' => '1.0.0',
        'order' => 4,
        'icon' => 'fas fa-calendar-alt',
        'route_prefix' => 'admin/agenda',
        'dependencies' => [],
    ],
    'midia' => [
        'name' => 'Mídia',
        'description' => 'Gerenciamento de arquivos de mídia e uploads',
        'active' => true,
        'version' => '1.0.0',
        'order' => 5,
        'icon' => 'fas fa-photo-video',
        'route_prefix' => 'admin/midia',
        'dependencies' => [],
    ],
    'transparencia' => [
        'name' => 'Transparência',
        'description' => 'Portal da transparência com dados públicos',
        'active' => true,
        'version' => '1.0.0',
        'order' => 6,
        'icon' => 'fas fa-eye',
        'route_prefix' => 'admin/transparencia',
        'dependencies' => [],
    ],
    'financeiro' => [
        'name' => 'Financeiro',
        'description' => 'Gestão financeira, despesas e receitas',
        'active' => true,
        'version' => '1.0.0',
        'order' => 7,
        'icon' => 'fas fa-money-bill-wave',
        'route_prefix' => 'admin/financeiro',
        'dependencies' => [],
    ],
    'contato' => [
        'name' => 'Contato',
        'description' => 'Formulários de contato e ouvidoria',
        'active' => true,
        'version' => '1.0.0',
        'order' => 8,
        'icon' => 'fas fa-envelope',
        'route_prefix' => 'admin/contato',
        'dependencies' => [],
    ],
    'newsletter' => [
        'name' => 'Newsletter',
        'description' => 'Gerenciamento de inscrições e disparos de newsletters',
        'active' => true,
        'version' => '1.0.0',
        'order' => 9,
        'icon' => 'fas fa-mail-bulk',
        'route_prefix' => 'admin/newsletter',
        'dependencies' => [],
    ],
    'seo' => [
        'name' => 'SEO',
        'description' => 'Otimização para mecanismos de busca',
        'active' => true,
        'version' => '1.0.0',
        'order' => 10,
        'icon' => 'fas fa-search',
        'route_prefix' => 'admin/seo',
        'dependencies' => [],
    ],
    'visitas' => [
        'name' => 'Visitas',
        'description' => 'Estatísticas de visitas e analytics',
        'active' => true,
        'version' => '1.0.0',
        'order' => 11,
        'icon' => 'fas fa-chart-line',
        'route_prefix' => 'admin/visitas',
        'dependencies' => [],
    ],
    'smtp' => [
        'name' => 'SMTP',
        'description' => 'Configuração de servidor de e-mail SMTP',
        'active' => true,
        'version' => '1.0.0',
        'order' => 12,
        'icon' => 'fas fa-envelope-open-text',
        'route_prefix' => 'admin/smtp',
        'dependencies' => [],
    ],
    'license' => [
        'name' => 'Licença',
        'description' => 'Gerenciamento de licenciamento do sistema',
        'active' => true,
        'version' => '1.0.0',
        'order' => 13,
        'icon' => 'fas fa-key',
        'route_prefix' => 'admin/license',
        'dependencies' => [],
    ],
    'backup' => [
        'name' => 'Backup',
        'description' => 'Gerenciamento de backups do sistema',
        'active' => true,
        'version' => '1.0.0',
        'order' => 14,
        'icon' => 'fas fa-database',
        'route_prefix' => 'admin/backup',
        'dependencies' => [],
    ],
    'waf' => [
        'name' => 'WAF',
        'description' => 'Firewall de aplicação web e segurança',
        'active' => true,
        'version' => '1.0.0',
        'order' => 15,
        'icon' => 'fas fa-shield-alt',
        'route_prefix' => 'admin/waf',
        'dependencies' => [],
    ],
    'logs' => [
        'name' => 'Logs',
        'description' => 'Registro de atividades e logs do sistema',
        'active' => true,
        'version' => '1.0.0',
        'order' => 16,
        'icon' => 'fas fa-clipboard-list',
        'route_prefix' => 'admin/logs',
        'dependencies' => [],
    ],
    'notificacoes' => [
        'name' => 'Notificações',
        'description' => 'Sistema de notificações internas',
        'active' => true,
        'version' => '1.0.0',
        'order' => 17,
        'icon' => 'fas fa-bell',
        'route_prefix' => 'admin/notificacoes',
        'dependencies' => [],
    ],
    'menus' => [
        'name' => 'Menus',
        'description' => 'Gerenciamento de menus de navegação',
        'active' => true,
        'version' => '1.0.0',
        'order' => 18,
        'icon' => 'fas fa-bars',
        'route_prefix' => 'admin/menus',
        'dependencies' => [],
    ],
    'settings' => [
        'name' => 'Configurações',
        'description' => 'Configurações gerais do sistema',
        'active' => true,
        'version' => '1.0.0',
        'order' => 19,
        'icon' => 'fas fa-cogs',
        'route_prefix' => 'admin/settings',
        'dependencies' => [],
    ],
];
